// flow-typed signature: e90c42042daa107acdf3d553be77871b
// flow-typed version: <<STUB>>/postcss-move-media_v^1.0.0-pre/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-move-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-move-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-move-media/index' {
  declare module.exports: $Exports<'postcss-move-media'>;
}
declare module 'postcss-move-media/index.js' {
  declare module.exports: $Exports<'postcss-move-media'>;
}
